replicaCount: 1

image:
  repository: public.ecr.aws/b4c0c6w7/tesis/tp1-backend
  tag: latest
  pullPolicy: Always

containerPort: 8080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
