replicaCount: 1

image:
  repository: public.ecr.aws/b4c0c6w7/tesis/tp1-frontend
  tag: latest
  pullPolicy: Always

containerPort: 3000

env:
  VITE_API_BASE_URL: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: app.local
      paths:
        - path: /api
          pathType: Prefix
          service:
            name: tp1-backend-service
            port: 8080
        - path: /
          pathType: Prefix
  tls: []

resources: {}
