apiVersion: v1
kind: Pod
metadata:
  name: memory-stress
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        requests:
          memory: "4000Mi"
        limits:
          memory: "5000Mi"
      command: ["stress"]
      args: ["--vm", "2", "--vm-bytes", "4000M", "--timeout", "300s"]
